import { BoardMapType } from "./types/boardMap.type";

export const boardMap: { [key: string]: BoardMapType } = {
  map1: {
    treasureAmount: 3,
    data: {
      "y-0-x-0": { val: 3 },
      "y-0-x-1": { val: 'T' },
      "y-0-x-2": { val: 3 },
      "y-0-x-3": { val: 2 },
      "y-0-x-4": { val: 1 },
      "y-1-x-0": { val: 2 },
      "y-1-x-1": { val: 3 },
      "y-1-x-2": { val: 2 },
      "y-1-x-3": { val: 3 },
      "y-1-x-4": { val: 2 },
      "y-2-x-0": { val: 1 },
      "y-2-x-1": { val: 2 },
      "y-2-x-2": { val: 3 },
      "y-2-x-3": { val: 'T' },
      "y-2-x-4": { val: 3 },
      "y-3-x-0": { val: 2 },
      "y-3-x-1": { val: 3 },
      "y-3-x-2": { val: 2 },
      "y-3-x-3": { val: 3 },
      "y-3-x-4": { val: 2 },
      "y-4-x-0": { val: 3 },
      "y-4-x-1": { val: 'T' },
      "y-4-x-2": { val: 3 },
      "y-4-x-3": { val: 2 },
      "y-4-x-4": { val: 1 },
    }
  },
  map2: {
    treasureAmount: 3,
    data: {
      "y-0-x-0": { val: 2 },
      "y-0-x-1": { val: 3 },
      "y-0-x-2": { val: 'T' },
      "y-0-x-3": { val: 3 },
      "y-0-x-4": { val: 2 },
      "y-1-x-0": { val: 1 },
      "y-1-x-1": { val: 2 },
      "y-1-x-2": { val: 3 },
      "y-1-x-3": { val: 2 },
      "y-1-x-4": { val: 3 },
      "y-2-x-0": { val: 2 },
      "y-2-x-1": { val: 1 },
      "y-2-x-2": { val: 2 },
      "y-2-x-3": { val: 3 },
      "y-2-x-4": { val: 'T' },
      "y-3-x-0": { val: 1 },
      "y-3-x-1": { val: 2 },
      "y-3-x-2": { val: 3 },
      "y-3-x-3": { val: 2 },
      "y-3-x-4": { val: 3 },
      "y-4-x-0": { val: 2 },
      "y-4-x-1": { val: 3 },
      "y-4-x-2": { val: 'T' },
      "y-4-x-3": { val: 3 },
      "y-4-x-4": { val: 2 },
    }
  },
  map3: {
    treasureAmount: 2,
    data: {
      "y-0-x-0": { val: 1 },
      "y-0-x-1": { val: 2 },
      "y-0-x-2": { val: 3 },
      "y-0-x-3": { val: 'T' },
      "y-0-x-4": { val: 3 },
      "y-1-x-0": { val: 2 },
      "y-1-x-1": { val: 1 },
      "y-1-x-2": { val: 2 },
      "y-1-x-3": { val: 3 },
      "y-1-x-4": { val: 2 },
      "y-2-x-0": { val: 3 },
      "y-2-x-1": { val: 2 },
      "y-2-x-2": { val: 1 },
      "y-2-x-3": { val: 2 },
      "y-2-x-4": { val: 3 },
      "y-3-x-0": { val: 2 },
      "y-3-x-1": { val: 1 },
      "y-3-x-2": { val: 2 },
      "y-3-x-3": { val: 3 },
      "y-3-x-4": { val: 2 },
      "y-4-x-0": { val: 1 },
      "y-4-x-1": { val: 2 },
      "y-4-x-2": { val: 3 },
      "y-4-x-3": { val: 'T' },
      "y-4-x-4": { val: 3 },
    }
  }
};